Header color change, fixes long list click
BuildmLearn/BuildmLearn-Toolkit-Android pull request #402
Opened 2017-01-20 11:57 UTC by akmittal006

a UI update which includes following:

1. change of header color based on type of template selected. Provides more continuity and feel to app.
![ezgif com-5da98cc0ca](https://cloud.githubusercontent.com/assets/8525715/22148649/5e20ef94-df35-11e6-86a8-6b698383bd62.gif)

2. Refactors some code

3. fixes #364

2017-02-08 11:11 UTC, opticod reviewed
@akmittal006, Thanks for these changes, but it looks like @vishwesh3 is also working for issue #364. Can you please remove the third fix from this PR, so that we can merge it. 

Note: Squash your commits into one , Thank you

2017-03-12 12:15 UTC, akmittal006 commented
@opticod it is done. 
Changes made - 
1. Header color change based on type of template
2. Refactoring of some code.

2017-03-14 01:15 UTC, opticod requested changes
Nice effort! But couple of comments.

2017-03-14 01:15 UTC, opticod commented on source-code/app/src/main/java/org/buildmlearn/toolkit/templates/ComprehensionAdapter.java
> +    private static  Context context;
Using static field for Context variable will lead to memory leak. You can many article on memory leak through static fields in web. 
Can you come up with different approach for this?

2017-03-14 01:15 UTC, opticod commented on source-code/app/src/main/java/org/buildmlearn/toolkit/templates/MatchAdapter.java
> +    private static  Context context;
Same here!

2017-03-14 11:20 UTC, akmittal006 commented
@opticod I have made the changes. Thanks for reviewing.

2017-03-14 12:28 UTC, opticod approved these changes
Thanks @akmittal006 Its looking as well as working great. :tada:

2017-03-14 12:29 UTC, merged